# Generated by Django 3.1.4 on 2021-01-07 20:46

from django.db import migrations, models
import transfer.models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20210107_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipientAccount',
            field=models.CharField(max_length=26, validators=[transfer.models.validate_account]),
        ),
    ]
