# Generated by Django 3.1.4 on 2021-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_auto_20210107_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
