# Generated by Django 3.1.4 on 2021-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_transfer_isconfirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='recipientName',
            field=models.CharField(max_length=300),
        ),
    ]
